### PR TITLE
Use logger in Link and IbcClient

### LINKED ISSUE #57: Add logger support to library
We should accept a [winstonjs](https://github.com/winstonjs/winston) compatible logger interface in Link, Endpoint, and IbcClient and produce debug/info/warn/error logging. Verbose should be every rpc call we make (debug with the entire payload), info the general actions token ("create connection musselnet {07-tendermint-5:connection-3} <=> bifrost {07-tendermint-2:connection-1}"), and warn/error only when there are problems.

Question whether the logger should be passed in every method call, or we should set it in the constructors.

Interface should be a subset of [`winstonjs.Logger`](https://github.com/winstonjs/winston/blob/master/index.d.ts#L89-L145). We can expand over time, but harder to reduce. My proposal is something like this (taking only one aspect of `LeveledLogMethod`):

```ts
interface Logger {
  error: (message: string, ...meta: any[]) => Logger,
  warn: (message: string, ...meta: any[]) => Logger,
  info: (message: string, ...meta: any[]) => Logger,
  verbose: (message: string, ...meta: any[]) => Logger,
  debug: (message: string, ...meta: any[]) => Logger,
}
```

Maybe we want to expose the `isDebugEnabled(): boolean`... methods as well to avoid doing unneeded calculations for the logger?

### PR DESCRIPTION
**Pull request by willclarktech**
Closes #57

Merge after #74

Logging level is `info` in `Link`, and `verbose`/`debug` in `IbcClient` except for creating
connections which is `info`.

### CODE REVIEW

File: src/lib/ibcclient.ts [hunk 1]
```diff
@@ -277,6 +284,9 @@ export class IbcClient {
   }
 
   public getCommit(height?: number): Promise<CommitResponse> {
+    this.logger.verbose(
+      height === undefined ? 'Get commit' : `Get commit for height ${height}`
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:288]: -> `undefined ? 'Get latest commit' : ...`

File: src/lib/ibcclient.ts [hunk 2]
```diff
@@ -529,6 +547,11 @@ export class IbcClient {
     msgs: EncodeObject[],
     fees: StdFee
   ): Promise<MsgResult> {
+    this.logger.verbose(`Broadcast multiple msgs`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:550]: :+1:

File: src/lib/ibcclient.ts [hunk 3]
```diff
@@ -663,6 +692,7 @@ export class IbcClient {
     myClientId: string,
     proof: ConnectionHandshakeProof
   ): Promise<CreateConnectionResult> {
+    this.logger.info(`Connection open try for my client ${myClientId}`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:695]: Listing at least (1) counterparty clientId and maybe (2) counterparty connection id would be nice.
Or maybe we log both connection IDs shortly before return? (We parse the newly defined one there)

File: src/lib/ibcclient.ts [hunk 4]
```diff
@@ -721,6 +752,7 @@ export class IbcClient {
     myConnectionId: string,
     proof: ConnectionHandshakeProof
   ): Promise<MsgResult> {
+    this.logger.info(`Connection open ack for my connection ${myConnectionId}`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:755]: Yes. Just connections here, not clients (we printed the connectionIDs before.

Let's add both connection IDs: `Connection open ack for ${myConnectionId} => ${proof.connectionId}`

File: src/lib/ibcclient.ts [hunk 5]
```diff
@@ -622,6 +649,7 @@ export class IbcClient {
     clientId: string,
     remoteClientId: string
   ): Promise<CreateConnectionResult> {
+    this.logger.info(`Connection open init: ${clientId} => ${remoteClientId}`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:652]: I like this format. Let's use a similar one (myId => remoteId) for all the connection handshake logs (and channel handshake too)

File: src/lib/ibcclient.ts [hunk 6]
```diff
@@ -801,6 +836,7 @@ export class IbcClient {
     connectionId: string,
     version: string
   ): Promise<CreateChannelResult> {
+    this.logger.verbose(`Channel open init: ${portId} => ${remotePortId}`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:839]: Maybe log the newly created channelID with `this.logger.debug` call right before the return?

File: src/lib/ibcclient.ts [hunk 7]
```diff
@@ -850,6 +887,7 @@ export class IbcClient {
     counterpartyVersion: string,
     proof: ChannelHandshake
   ): Promise<CreateChannelResult> {
+    this.logger.verbose(`Channel open try for port ${portId}`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:890]: Let's show both ports (and the remote channel), as in the ChannelOpenInit call

File: src/lib/ibcclient.ts [hunk 8]
```diff
@@ -899,6 +938,9 @@ export class IbcClient {
     counterpartyVersion: string,
     proof: ChannelHandshake
   ): Promise<MsgResult> {
+    this.logger.verbose(
+      `Channel open ack for port ${portId}: ${channelId} => ${counterpartyChannelId}`
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:942]: :+1:

File: src/lib/ibcclient.ts [hunk 9]
```diff
@@ -935,6 +978,9 @@ export class IbcClient {
     channelId: string,
     proof: ChannelHandshake
   ): Promise<MsgResult> {
+    this.logger.verbose(
+      `Chanel open confirm for port ${portId} and channel ${channelId}`
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:982]: :+1:

File: src/lib/ibcclient.ts [hunk 10]
```diff
@@ -1110,6 +1163,7 @@ export class IbcClient {
     timeoutBlock?: number,
     timeoutTime?: number
   ): Promise<MsgResult> {
+    this.logger.verbose(`Transfer tokens to ${receiver}`);
```
Comment (ethanfrey) [inline src/lib/ibcclient.ts:1166]: Is there a nice stringify method for Coin?

`Transfer ${prettyToken(token)} to ${receiver}`

Comment (ethanfrey) [reply src/lib/ibcclient.ts:1166]: Actually, this will only be used in tests likely, so no big deal

File: src/lib/link.spec.ts [hunk 11]
```diff
@@ -4,12 +4,20 @@ import test from 'ava';
...
+  ics20,
+  randomAddress,
+  setup,
+  simapp,
+  TestLogger,
+  wasmd,
+} from './testutils.spec';
 
 test.serial('establish new client-connection', async (t) => {
+  const logger = new TestLogger();
```
Comment (ethanfrey) [inline src/lib/link.spec.ts:17]: So, if I want detailed logs from this method, I would just use `const logger = new TestLogger(true)` ?

File: src/lib/link.ts [hunk 12]
```diff
@@ -258,6 +264,9 @@ export class Link {
     source: Side,
     minHeight: number
   ): Promise<number> {
+    this.logger.info(
+      `Update client for source ${source} to min height ${minHeight}`
```
Comment (ethanfrey) [inline src/lib/link.ts:268]: This will call the above method (with log) if we need to update.
Maybe, `this.logger.info(`Checking if client for source ${source} >= height ${minHeight}` or something similar.

File: src/lib/link.ts [hunk 13]
```diff
@@ -406,6 +419,7 @@ export class Link {
 
   // Returns the last height that this side knows of the other blockchain
   public async lastKnownHeader(side: Side): Promise<number> {
+    this.logger.info(`Get last known header for side ${side}`);
```
Comment (ethanfrey) [inline src/lib/link.ts:422]: This should be verbose.
Actually, I think most of the queries (besides the updateClient ones) should be on verbose level

**Review by ethanfrey — APPROVED** [review]
Looks good.

Can you do a little cleanup and a rebase, then good to merge.

File: src/lib/link.spec.ts (hunk 11 above)
Comment (willclarktech) [reply src/lib/link.spec.ts:17]: Yes, passing `true` will turn on console logging for all levels. Does it need to be configurable? I was imagining that if we wanted to see what was being logged while running tests it would be temporary and we'd want to see everything.

Comment (ethanfrey) [reply src/lib/link.spec.ts:17]: That sounds good. And we can enable it on a per-test basis.

Seems like a good design, I just wanted to ensure I understood
